### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by RobinSmithTHR** [grncdr/node-any-db#110]
Receiving the following error while trying to update any-db-mysql.

npm ERR! While resolving: QueryLoader@2.8.21
npm ERR! Found: any-db@2.2.1
npm ERR! node_modules/any-db
npm ERR!   any-db@"^2.2.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer any-db@"~2.1.0" from any-db-mysql@2.3.0
npm ERR! node_modules/any-db-mysql
npm ERR!   any-db-mysql@"^2.3.0" from the root project

**Comment by grncdr** [comment]
Hi @RobinSmithTHR not sure if you've seen the [project status in the README](https://github.com/grncdr/node-any-db#status) but I'd strongly recommend that if you have a project that relies on any-db, you move to something else as soon as possible.

If you only need to support using MySQL, there's _very_ little API difference between `any-db-mysql` and using the `mysql` package directly, it's probably simplest to just migrate first to [mysql@2.13.0](https://github.com/grncdr/node-any-db/blob/master/packages/any-db-mysql/package.json#L27) and then upgrade the mysql package from there.

If you *do* need to keep using any-db for some reason, I'm happy to review PRs that get things working for you again.
