### ISSUE TITLE
Plugin architecture

### ISSUE THREAD

**Issue by stevenvachon** [grncdr/node-any-db#68]
Might be a better approach so that support for "any db" could be added :)

MongoDB and RethinkDB would be awesome plugins.

**Comment by grncdr** [comment]
Any-DB already *is* a plugin architecture, there's nothing stopping somebody from writing `any-db-mongo`. However, I've got zero interest in doing it myself. In the future I will be moving away from the plugin-registry pattern used here in favour of requiring users to combine adapters and pools within their own code.
