### ISSUE TITLE
Use socket path for db connection

### ISSUE THREAD

**Issue by Dortamur** [grncdr/node-any-db#72]
Is there any way to use a socket file to connect to a database, such as MySQL, instead of requiring a net connection? We have some environments that only use sockets for connecting to DBs.

The node mysql module supports it through the socketPath connection option - is there a way to specify this option when connecting through any-db?

**Comment by grncdr** [comment]
Yes, simply require('any-db-mysql') instead of any-db, and you can pass a mysql options object instead of a database URL.
